from __future__ import annotations

from app.providers.base import ProviderDefinition

PROVIDER_DEFINITIONS: tuple[ProviderDefinition, ...] = (
    ProviderDefinition(
        id="receive_smss",
        name="Receive SMSS",
        homepage_url="https://receive-smss.com/",
        transport_mode="httpx",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="none",
        enabled=True,
        priority=10,
        notes="Tier A default pool backbone.",
    ),
    ProviderDefinition(
        id="temp_number",
        name="Temp Number",
        homepage_url="https://temp-number.com/",
        transport_mode="flaresolverr",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="cookie_clearance",
        enabled=True,
        priority=20,
        notes="Tier A default pool backbone; strongest freshness in current validation.",
    ),
    ProviderDefinition(
        id="sms24",
        name="SMS24",
        homepage_url="https://sms24.me/",
        transport_mode="flaresolverr",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="cookie_clearance",
        enabled=True,
        priority=30,
        notes="Tier A default pool backbone; freshness filter required at number level.",
    ),
    ProviderDefinition(
        id="smstome",
        name="SMSToMe",
        homepage_url="https://smstome.com/",
        transport_mode="flaresolverr",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="cookie_clearance",
        enabled=True,
        priority=40,
        notes="Tier A default pool backbone.",
    ),
    ProviderDefinition(
        id="receive_sms_free_cc",
        name="Receive SMS Free CC",
        homepage_url="https://receive-sms-free.cc/",
        transport_mode="flaresolverr",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="cookie_clearance",
        enabled=True,
        priority=50,
        notes="Tier B fallback provider.",
    ),
    ProviderDefinition(
        id="jiemahao",
        name="接码号",
        homepage_url="https://jiemahao.com/",
        transport_mode="flaresolverr",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="cookie_clearance",
        enabled=True,
        priority=60,
        notes="Tier B fallback provider; strong dirty-data filtering required.",
    ),
    ProviderDefinition(
        id="quackr",
        name="Quackr",
        homepage_url="https://quackr.io/",
        transport_mode="httpx",
        discovery_mode="json",
        detail_mode="json_api",
        auth_mode="turnstile_token",
        enabled=False,
        priority=70,
        notes="Discovery works through numbers.json; message API still requires extra verification.",
    ),
    ProviderDefinition(
        id="temporary_phone_number",
        name="Temporary Phone Number",
        homepage_url="https://temporary-phone-number.com/",
        transport_mode="flaresolverr",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="cookie_clearance",
        enabled=False,
        priority=80,
        notes="Excluded from default pool because some pages are login-gated.",
    ),
    ProviderDefinition(
        id="freephonenum",
        name="FreePhoneNum",
        homepage_url="https://freephonenum.com/",
        transport_mode="flaresolverr",
        discovery_mode="html",
        detail_mode="html",
        auth_mode="cookie_clearance",
        enabled=False,
        priority=90,
        notes="Excluded from default pool due to empty or very old message histories.",
    ),
    ProviderDefinition(
        id="receivesms_org",
        name="ReceiveSMS.org",
        homepage_url="https://www.receivesms.org/",
        transport_mode="httpx",
        discovery_mode="seed_only",
        detail_mode="html",
        auth_mode="none",
        enabled=False,
        priority=100,
        notes="Excluded from default pool; current sample pages are months stale.",
    ),
)


def get_provider_definitions() -> tuple[ProviderDefinition, ...]:
    return PROVIDER_DEFINITIONS
